export const sponsorList = [
    "Airstack",      
    "Celo",      
    "Graph",            
    "Metamask",          
    "Polygon",           
    "Scroll",            
    "Zetachain",
    "Alliance",           
    "Chainlink",         
    "Huddle01",         
    "Mona",           
    "Powerloom",       
    "Waku",
    "Arbitrum",   
    "Ethereum Foundation",
    "Lighthouse Storage",
    "OKX",        
    "Push Protocol",
    "XDM",
    "Base",    
    "Filecoin",      
    "Mantle",           
    "Octo",             
    "Safe",              
    "XMTP",
]